config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users do
    collection do
      get 'login'
    end
  end
  resources :groups do
    resources :messages do
      resources :chats  do
      end
      collection do
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :message
  belongs_to :group
  belongs_to :user
  validates :comment, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  has_many :chats
  validates :name, presence: true, uniqueness: true
end

# , unless: :image?

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :chats
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

  def self.search(search)
    if search
      where(['content LIKE ?', "%#{search}%"]) 
    else
      all #全て表示させる
   end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :chats

  validates :name, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :move_to_index, except: [:index]
  def index
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @chat = Chat.new
    @messages = @group.messages
    @chats = @message.chats.includes(:user).page(params[:page]).per(10)
  end

  def create
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @chat = Chat.create(chat_params)
    if @chat.save
      respond_to do |format|
        format.html { redirect_to group_message_chats_path(@chat.group_id,@chat.message_id) }
        format.json
      end
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:message_id])
    @chat = Chat.find(params[:id])
    @chat.destroy
    redirect_to group_message_chats_path(@chat.group_id,@chat.message_id)
  end

  private

  def chat_params
    params.require(:chat).permit(:comment).merge(user_id: current_user.id,group_id:@group.id,message_id:@message.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :move_to_index, except: [:index]
  def index
    @groups = Group.all.page(params[:page]).per(10)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(group_params)
    if @group.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to root_path
  end
   
private

  def group_params
    params.require(:group).permit(:name, :image).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :move_to_index, except: [:index, :search]

  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user)
    @message = Message.new
  end

  def create
    @group = Group.find(params[:group_id])
    @message = Message.create(message_params)
    if @message.save
      redirect_to group_messages_path(@group.id)
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    redirect_to group_messages_path(@message.group_id)
  end

  def edit
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @message = Message.find(params[:id])
    @message.update(message_params)
    redirect_to group_messages_path(@group.id,@message.id)
  end

  def search
    @group = Group.find(params[:group_id])
    @messages = Message.search(params[:search]).page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.json
    end
  end

private

  def message_params
    params.require(:message).permit(:content,:text,:image,:keyword).merge(user_id: current_user.id,group_id:@group.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect to root path
  end
  
  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  def login
  end


private

  def user_params
    params.require(:user).permit(:name, :email,:region)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/index.html.haml
.wrapper
  = render "groups/header"
  .main
    .content
      .content__main
        .chat__main__form
          = form_for [@group,@message,@chat],id:"new_chat",method: :post,url: group_message_chats_path(@group.id,@message.id,@chat.id) do |f|
            = f.text_field :comment, class: 'chat__main__form__message', placeholder: 'type a message'
            .chat__main__form__mask
            = f.submit 'Send', class: 'form__submit'
        .chat-space
          - @chats.each do |chat|
            .chat-box
              .chat-box-content
                .chat-box-content__text
                  .user-name
                    = chat.user.name
                    さん
                  .comment
                    = chat.comment
                  .created-at
                    = chat.created_at.strftime("%Y/%m/%d %H:%M")
                - if user_signed_in? && current_user.id == chat.user_id
                  .more
                    .more_list
                      = button_to group_message_chat_path(@group.id,@message.id,chat.id), method: :delete,class: "button" do
                        削除
                -else
                  .more
  .paginate
    = paginate(@chats)
    

app/views/groups/_header.html.haml
.header
  .header__title
    =link_to root_path class:"header__title" do
      HoBBies
  .post
    - if user_signed_in?
      .post-btn
        =link_to new_group_path ,class: "post-btn" do
          .post-btn__wide
            .post-btn__wide__content
              .post-btn__wide__content__text
                ジャンル追加
              .post-btn__wide__content__icon
                %i.fa.fa-box
    - else
  .header__user-btn
    .newuser-btn
      - if user_signed_in?
        =link_to edit_user_path(current_user.id) do
          マイページ
      - else 
        =link_to users_path do
          新規登録
    .login-btn
      - if user_signed_in?
        =link_to destroy_user_session_path, method: :delete do 
          ログアウト
        .current_user_name
          = current_user.name
          さん
      - else
        = link_to "ログイン", new_user_session_path
  

app/views/groups/edit.html.haml
.wrapper
  = render "header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            編集
          .registration-form
            = form_for @group,method: :patch,url:group_path(@group.id) do |f|
              .form-contents
                .form-group
                  %label{for: "name"} 
                  = f.text_field :name, class:'input-default', placeholder: 'ジャンル'
                  %span.require-message 必須
                .form__mask
                  = f.label :image, class: 'form__mask__image' do
                    = icon('fas', 'image', class: 'icon')
                    = f.file_field :image, class: 'hidden'
                .form-group 
                =f.submit "Edit" ,class:"btn-red", type:"submit"

app/views/groups/index.html.haml
.wrapper
  = render "header"
  .main
    .content
      .hobbys
        - @groups.each do |group|
          .hobby-box
            =link_to group_messages_path(group.id) do
              .hobby-image
                - if group.image.url nil?
                  =image_tag group.image.url,size: "200x200"
                - else
                  =image_tag "/images/sample_img.gif",size: "200x200"
              .hobby-content
                = group.name
            - if user_signed_in? && current_user.id == group.user_id
              .more
                .more_list
                  = button_to group_path(group.id), method: :delete,class: "button" do
                    削除
                  = button_to edit_group_path(group.id), method: :get,class: "button" do  
                    編集
            -else
              .more
              
  .paginate
    = paginate(@groups)
    

app/views/groups/new.html.haml
.wrapper
  = render "header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            ジャンル追加
          .registration-form
            = form_for @group,method: :post,url:groups_path(@group.id) do |f|
              .form-contents
                .form-group
                  %label{for: "name"} 
                  = f.text_field :name, class:'input-default', placeholder: 'ジャンル'
                  %span.require-message 必須
                .form__mask
                  = f.label :image, class: 'form__mask__image' do
                    = icon('fas', 'image', class: 'icon')
                    = f.file_field :image, class: 'hidden'
                .form-group 
                =f.submit "追加" ,class:"btn-red", type:"submit"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HobyApp</title>
    <%= csrf_meta_tags %>
    <%=  csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.haml
.wrapper
  = render "groups/header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            編集
          .registration-form
            = form_for [@group,@message], url:group_message_path(@group.id,@message.id) do |f|
              .form-contents
                .formblock1
                  .form-group
                    %label{for: "content"} 
                    = f.text_field :content, class:'input-default', placeholder: '題名'
                    %span.require-message 必須
                  .form__mask
                    = f.label :image, class: 'form__mask__image' do
                      = icon('fas', 'image', class: 'icon')
                      = f.file_field :image, class: 'hidden'
                .formblock2
                  .form-group
                    %label{for: "text"} 
                    = f.text_area :text, class:'input-default2', placeholder: '説明'
                    %span.require-message 必須
                  .form-group 
                  =f.submit "Edit" ,class:"btn-red", type:"submit"

app/views/messages/index.html.haml
.wrapper
  = render "groups/header"
  .main
    .main-header
      - if user_signed_in? 
        .post-btn
          =link_to new_group_message_path(@group.id) ,class: "post-btn" do
            .post-btn__wide
              .post-btn__wide__content
                .post-btn__wide__content__text
                  投稿
                .post-btn__wide__content__icon
                  %i.fa.fa-pen-nib
      .form
        = form_tag search_group_messages_path(@group.id),local: true, method: :get, class: "search-form" do
          = text_field_tag ":search", "", {class: "search-form", id: "test-id"}
          = submit_tag "検索",content: nil, class: "search-btn"
        -# = form_with(url: search_group_messages_path(@group.id), local: true, method: :get, class: "search-form") do |form|
        -#   = form.text_field :search, placeholder: "投稿を検索する", class: "search-input"
        -#   = form.submit "検索",content: nil, class: "search-btn"
    .content
      .group-name
        = @group.name
      .review
        - @messages.each do |message|
          .review__box
            .review__box__image
              - if message.image.url nil?
                =image_tag message.image.url,size: "200x200"
              - else
                =image_tag "/images/sample_img.gif",size: "200x200"
            .review__box__contents
              .review__box__contents__content
                .review__box__contents__content__message
                  = message.content
                .right_username
                  = message.user.name
                  さん
              - if user_signed_in? && current_user.id == message.user_id
                .more
                  .more_list
                    = button_to group_message_path(@group.id,message.id), method: :delete,class: "button" do
                      削除
                    = button_to edit_group_message_path(@group.id,message.id), method: :get,class: "button" do
                      編集
              -else
              .review__box__text
                = message.text
              - if user_signed_in? 
                .link-to-chat
                  =link_to group_message_chats_path(@group.id,message.id) do
                    チャット
              - else
    .paginate
      = paginate(@messages)

app/views/messages/new.html.haml
.wrapper
  = render "groups/header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            投稿
          .registration-form
            = form_for [@group, @message], method: :post,url:group_messages_path(@group.id) do |f|
              .form-contents
                .formblock1
                  .form-group
                    %label{for: "content"} 
                    = f.text_field :content, class:'input-default', placeholder: '題名'
                    %span.require-message 必須
                  .form__mask
                    = f.label :image, class: 'form__mask__image' do
                      = icon('fas', 'image', class: 'icon')
                      = f.file_field :image, class: 'hidden'
                .formblock2
                  .form-group
                    %label{for: "text"} 
                    = f.text_area :text, class:'input-default2', placeholder: '説明'
                    %span.require-message 必須
                  .form-group 
                  =f.submit "投稿" ,class:"btn-red", type:"submit"

app/views/messages/search.html.haml
.wrapper
  = render "groups/header"
  .main
    .form
      = form_tag search_group_messages_path(@group.id),local: true, method: :get, class: "search-form" do
        = text_field_tag :search
        = submit_tag "検索",content: nil, class: "search-btn"
    - if user_signed_in? 
      .post-btn
        =link_to new_group_message_path(@group.id) ,class: "post-btn" do
          .post-btn__wide
            .post-btn__wide__content
              .post-btn__wide__content__text
                投稿
              .post-btn__wide__content__icon
                %i.fa.fa-pen-nib
    - else
    .content
      .group-name
        = @group.name
      .review
        - @messages.each do |message|
          .review__box
            .review__box__image
              =image_tag message.image.url,size: "188x188"if message.image.present?
            .review__box__contents
              .review__box__contents__content
                = message.content
              .right_username
                = message.user.name
                さん
              .review__box__contents__text
                = message.text
              - if user_signed_in? 
                .link-to-chat
                  =link_to group_message_chats_path(@group.id,message.id) do
                    チャット
              - else
  .paginate
    = paginate(@messages)

app/views/users/edit.html.haml
.wrapper
  = render "groups/header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            会員情報
          .registration-form
            = form_for @user,method: :patch,url:user_path(@user.id) do |f|
              .form-contents
                .form-group
                  %label{for: "nickname"} ニックネーム
                  %span.require-message 必須
                  = f.text_field :name, class:'input-default', placeholder: 'ニックネーム'
                .form-group
                  %label{for: "email"} メールアドレス
                  %span.require-message 必須
                  = f.email_field :email,class:'input-default', placeholder: 'PC・携帯どちらでも可'
                %input{name: "login_type",type: "hidden",value: ""}/
                .form-group.form-password-revelation
                  %label{for: "password"} パスワード
                  %span.require-message 必須
                  = f.password_field :password, class:'input-default',placeholder: '6文字以上'
                  .form-password-revelation-toggle
                    .checkbox-default
                      = f.password_field :password_confirmation, class:'input-default' ,placeholder: '6文字以上'
                .form-group
                  %label{for: "prefecture"}
                    地域
                  %span.require
                    必須
                  .select-wrap
                    %i.arrow-bottom
                    = f.select :region, [["---", "---"], ["北海道", "北海道"], ["青森県", "青森県"], ["岩手県", "岩手県"], ["宮城県", "宮城県"], ["秋田県", "秋田県"], ["山形県", "山形県"], ["福島県", "福島県"], ["茨城県", "茨城県"], ["栃木県", "栃木県"], ["群馬県", "群馬県"], ["埼玉県", "埼玉県"], ["千葉県", "千葉県"], ["東京都", "東京都"], ["神奈川県", "神奈川県"], ["新潟県", "新潟県"], ["富山県", "富山県"], ["石川県", "石川県"], ["福井県", "福井県"], ["山梨県", "山梨県"], ["長野県", "長野県"], ["岐阜県", "岐阜県"], ["静岡県", "静岡県"], ["愛知県", "愛知県"], ["三重県", "三重県"], ["滋賀県", "滋賀県"], ["京都府", "京都府"], ["大阪府", "大阪府"], ["兵庫県", "兵庫県"], ["奈良県", "奈良県"], ["和歌山県", "和歌山県"], ["鳥取県", "鳥取県"], ["島根県", "島根県"], ["岡山県", "岡山県"], ["広島県", "広島県"], ["山口県", "山口県"], ["徳島県", "徳島県"], ["香川県", "香川県"], ["愛媛県", "愛媛県"], ["高知県", "高知県"], ["福岡県", "福岡県"], ["佐賀県", "佐賀県"], ["長崎県", "長崎県"], ["熊本県", "熊本県"], ["大分県", "大分県"], ["宮崎県", "宮崎県"], ["鹿児島県", "鹿児島県"], ["沖縄県", "沖縄県"],["未定", "未定"]],class:"form-control"
                .form-group 
                  =f.submit "変更", class:"btn_red", type:"submit"
                     

app/views/users/index.html.haml
.wrapper
  = render "groups/header"
  .main
    .content
      .content__main
        .container
          %h2.registration
            新規会員登録
          .registration-form
            = form_for @user, method: :post,url: users_path  do |f|
              .form-contents
                .form-group
                  %label{for: "nickname"} ニックネーム
                  %span.require-message 必須
                  = f.text_field :name, autofocus: true, maxlength: "6", class:'input-default', placeholder: 'ニックネーム'
                .form-group
                  %label{for: "email"} メールアドレス
                  %span.require-message 必須
                  = f.email_field :email,class:'input-default', placeholder: 'PC・携帯どちらでも可'
                %input{name: "login_type",type: "hidden",value: ""}/
                .form-group.form-password-revelation
                  %label{for: "password"} パスワード
                  %span.require-message 必須
                  = f.password_field :password, class:'input-default',placeholder: '6文字以上'
                  .form-password-revelation-toggle
                    .checkbox-default
                      = f.password_field :password_confirmation, class:'input-default' ,placeholder: '6文字以上'
                .form-group 
                  =f.submit "登録" ,class:"btn-red", type:"submit"               
  .footer
  